### ISSUE TITLE
./gradlew populate   is not working

### ISSUE THREAD

**Issue by cvertan** [thesaurus-linguae-aegyptiae/tla-common#6]
jdk 11.0.11.9 installed.
JAVA_HOME variable correct
checked if java and javac point to the same version
Elastic search started 
System variables identic as settings @dwerning and @RDBloese  where it works.
./gradlew updateDependencies  build successful
./gradlew populate does not work 
Error in attached file
[error.log](https://github.com/thesaurus-linguae-aegyptiae/tla-common/files/6700948/error.log)

**Comment by JKatzwinkel** [comment]
`tla-common` is a library modeling POJOs for data and command object transfer and has no concept of populating a search engine. I take it this issue has since been resolved?
